### ISSUE TITLE
fatal error when running yasca.sh

### ISSUE THREAD

**Issue by lilmike** [scovetta/yasca#11]
When I run yasca.sh --help from the main checkout of yasca.git, I get:

Fatal error: Uncaught Error: Class 'Yasca\Scanner' not found in /home/lilmike/yasca/Yasca/Main.php:37
Stack trace:
#0 /home/lilmike/yasca/Yasca/Main.php(358): {closure}()
#1 /home/lilmike/yasca/Yasca/Start.php(14): include('/home/lilmike/y...')
#2 {main}
  thrown in /home/lilmike/yasca/Yasca/Main.php on line 37

Any idea?
-Michael.

**Comment by zeeshankhurshid** [comment]
On line 37 of Main.php, there is a bug '+' is written in place of 'dot(.)' for concatanation. Remove this, it will start working.

**Comment by ib-tardis** [comment]
Hi @lilmike,

Is @zeeshankhurshid's solution working for ou? for me it is still issue.

Thanks in advance!
Imran
