### ISSUE TITLE
linux not found when starting yasca 

### ISSUE THREAD

**Issue by wassilaahamila** [scovetta/yasca#7]
root@wassila-VPCEH3U1E:/home/wassila/scovetta-yasca-ffd5e93# sh yasca.sh
yasca.sh: 9: yasca.sh: linux: not found
Failed loading ./opcache.so:  ./opcache.so: cannot open shared object file: No such file or directory
PHP Warning:  PHP Startup: Unable to load dynamic library './pdo.so' - ./pdo.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library './json.so' - ./json.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library './readline.so' - ./readline.so: cannot open shared object file: No such file or directory in Unknown on line 0

Fatal error: Uncaught exception 'LogicException' with message 'Class Yasca\Scanner could not be loaded' in /home/wassila/scovetta-yasca-ffd5e93/Yasca/Main.php:37
Stack trace:
#0 /home/wassila/scovetta-yasca-ffd5e93/Yasca/Main.php(37): spl_autoload('Yasca\Scanner')
#1 [internal function]: {closure}()
#2 /home/wassila/scovetta-yasca-ffd5e93/Yasca/Main.php(358): call_user_func(Object(Closure))
#3 /home/wassila/scovetta-yasca-ffd5e93/Yasca/Start.php(14): include('/home/wassila/s...')
#4 {main}
  thrown in /home/wassila/scovetta-yasca-ffd5e93/Yasca/Main.php on line 37

**Comment by zeeshankhurshid** [comment]
On line 37 of Main.php, there is a bug '+' is written in place of 'dot(.)' for concatanation. Remove this, it will start working.
