### ISSUE TITLE
Yacha - not able to generate xml or json report

### ISSUE THREAD

**Issue by ranjithmnair1976** [scovetta/yasca#8]
D:\software\yasca-tool\scovetta-yasca-ffd5e93>yasca --report,JSONFileReport d:\code

It is throwing error:

 Fatal error: Uncaught exception 'Yasca\Core\IteratorException' with message 'Key
 not found in collection' in D:\software\yasca-tool\scovetta-yasca-ffd5e93\Yasca
\Core\Iterators.php:164
Stack trace:
#0 D:\software\yasca-tool\scovetta-yasca-ffd5e93\Yasca\Core\Operators.php(77): Y
asca\Core\Iterators::elementAt(Array, 0)
#1 D:\software\yasca-tool\scovetta-yasca-ffd5e93\Yasca\Core\FunctionPipe.php(32)
: Yasca\Core\Operators::invokeArray(Array, Array)
#2 D:\software\yasca-tool\scovetta-yasca-ffd5e93\Yasca\Reports\JsonFileReport.ph
p(27): Yasca\Core\FunctionPipe->pipe(Array, 0)
#3 D:\software\yasca-tool\scovetta-yasca-ffd5e93\Yasca\Main.php(179): Yasca\Repo
rts\JsonFileReport->__construct(Array)
#4 [internal function]: {closure}()
#5 D:\software\yasca-tool\scovetta-yasca-ffd5e93\Yasca\Main.php(358): call_user_
func(Object(Closure))
#6 D:\software\yasca-tool\scovetta-yasca-ffd5e93\Yasca\Start.php(14): include('D
:\software\yas...')
#7 {main}
  thrown in D:\software\yasca-tool\scovetta-yasca-ffd5e93\Yasca\Core\Iterators.p
hp on line 164

**Comment by Harshal1693** [comment]
I was able to generate xml report but was unsuccessful with json report. Use version (2.2) for the xml format.
